package com.verdantartifice.primalmagick.test;

import com.verdantartifice.primalmagick.common.blocks.BlocksPM;
import com.verdantartifice.primalmagick.common.damagesource.DamageSourcesPM;
import com.verdantartifice.primalmagick.common.items.ItemsPM;
import com.verdantartifice.primalmagick.common.registries.IRegistryItem;
import com.verdantartifice.primalmagick.common.sources.Sources;
import com.verdantartifice.primalmagick.common.spells.payloads.BloodDamageSpellPayload;
import com.verdantartifice.primalmagick.common.spells.payloads.EarthDamageSpellPayload;
import com.verdantartifice.primalmagick.common.spells.payloads.SpellPayloadsPM;
import com.verdantartifice.primalmagick.common.wands.WandCap;
import com.verdantartifice.primalmagick.common.wands.WandCore;
import com.verdantartifice.primalmagick.common.wands.WandGem;
import com.verdantartifice.primalmagick.platform.Services;
import com.verdantartifice.primalmagick.test.attunements.AttunementTests;
import com.verdantartifice.primalmagick.test.capabilities.PlayerKnowledgeTests;
import com.verdantartifice.primalmagick.test.capabilities.ItemHandlerTests;
import com.verdantartifice.primalmagick.test.crafting.RepairTests;
import com.verdantartifice.primalmagick.test.crafting.RunecarvingTests;
import com.verdantartifice.primalmagick.test.crafting.CraftingRequirementsTests;
import com.verdantartifice.primalmagick.test.crafting.CalcinatorTests;
import com.verdantartifice.primalmagick.test.crafting.ArcaneWorkbenchTests;
import com.verdantartifice.primalmagick.test.enchantments.RitualEnchantmentTests;
import com.verdantartifice.primalmagick.test.enchantments.CasterEnchantingTests;
import com.verdantartifice.primalmagick.test.ftux.FtuxTests;
import com.verdantartifice.primalmagick.test.items.WandComponentTests;
import com.verdantartifice.primalmagick.test.items.WandManaTests;
import com.verdantartifice.primalmagick.test.items.DispenserTests;
import com.verdantartifice.primalmagick.test.items.BeeswaxTests;
import com.verdantartifice.primalmagick.test.research.ResearchTests;
import com.verdantartifice.primalmagick.test.research.ResearchRequirementsTests;
import com.verdantartifice.primalmagick.test.research.ResearchKeysTests;
import com.verdantartifice.primalmagick.test.spells.SpellPackageTests;
import com.verdantartifice.primalmagick.test.spells.WandSpellcastTests;
import com.verdantartifice.primalmagick.test.tiles.WandChargerTests;
import com.verdantartifice.primalmagick.test.tiles.ManaFontTests;
import com.verdantartifice.primalmagick.test.tiles.ManaBatteryTests;
import com.verdantartifice.primalmagick.test.tiles.AutoChargerTests;
import net.minecraft.gametest.framework.GameTestHelper;
import net.minecraft.world.damagesource.DamageSources;
import net.minecraft.world.level.block.Blocks;

import java.util.Set;
import java.util.function.Consumer;

public class TestFunctionsPM {
    public static void init() {
        // Pass the service initialization through this class so it gets class loaded and fields registered
        Services.TEST_FUNCTIONS_REGISTRY.init();
    }

    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> CANARY = Services.TEST_FUNCTIONS_REGISTRY.register("canary", () -> CanaryTest::canary);

    // Attunement buff tests
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> MINOR_ATTUNEMENT_DISCOUNT_EARTH = Services.TEST_FUNCTIONS_REGISTRY.register("minor_attunement_gives_mana_discount_earth", () -> (helper) -> AttunementTests.minor_attunement_gives_mana_discount(helper, Sources.EARTH));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> MINOR_ATTUNEMENT_DISCOUNT_SEA = Services.TEST_FUNCTIONS_REGISTRY.register("minor_attunement_gives_mana_discount_sea", () -> (helper) -> AttunementTests.minor_attunement_gives_mana_discount(helper, Sources.SEA));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> MINOR_ATTUNEMENT_DISCOUNT_SKY = Services.TEST_FUNCTIONS_REGISTRY.register("minor_attunement_gives_mana_discount_sky", () -> (helper) -> AttunementTests.minor_attunement_gives_mana_discount(helper, Sources.SKY));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> MINOR_ATTUNEMENT_DISCOUNT_SUN = Services.TEST_FUNCTIONS_REGISTRY.register("minor_attunement_gives_mana_discount_sun", () -> (helper) -> AttunementTests.minor_attunement_gives_mana_discount(helper, Sources.SUN));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> MINOR_ATTUNEMENT_DISCOUNT_MOON = Services.TEST_FUNCTIONS_REGISTRY.register("minor_attunement_gives_mana_discount_moon", () -> (helper) -> AttunementTests.minor_attunement_gives_mana_discount(helper, Sources.MOON));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> MINOR_ATTUNEMENT_DISCOUNT_BLOOD = Services.TEST_FUNCTIONS_REGISTRY.register("minor_attunement_gives_mana_discount_blood", () -> (helper) -> AttunementTests.minor_attunement_gives_mana_discount(helper, Sources.BLOOD));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> MINOR_ATTUNEMENT_DISCOUNT_INFERNAL = Services.TEST_FUNCTIONS_REGISTRY.register("minor_attunement_gives_mana_discount_infernal", () -> (helper) -> AttunementTests.minor_attunement_gives_mana_discount(helper, Sources.INFERNAL));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> MINOR_ATTUNEMENT_DISCOUNT_VOID = Services.TEST_FUNCTIONS_REGISTRY.register("minor_attunement_gives_mana_discount_void", () -> (helper) -> AttunementTests.minor_attunement_gives_mana_discount(helper, Sources.VOID));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> MINOR_ATTUNEMENT_DISCOUNT_HALLOWED = Services.TEST_FUNCTIONS_REGISTRY.register("minor_attunement_gives_mana_discount_hallowed", () -> (helper) -> AttunementTests.minor_attunement_gives_mana_discount(helper, Sources.HALLOWED));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> LESSER_EARTH_ATTUNEMENT_BUFF = Services.TEST_FUNCTIONS_REGISTRY.register("lesser_earth_attunement_gives_haste_modifier", () -> AttunementTests::lesser_earth_attunement_gives_haste_modifier);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> GREATER_EARTH_ATTUNEMENT_BUFF = Services.TEST_FUNCTIONS_REGISTRY.register("greater_earth_attunement_gives_step_height_modifier", () -> AttunementTests::greater_earth_attunement_gives_step_height_modifier);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> LESSER_SEA_ATTUNEMENT_BUFF = Services.TEST_FUNCTIONS_REGISTRY.register("lesser_sea_attunement_gives_increased_swim_speed", () -> AttunementTests::lesser_sea_attunement_gives_increased_swim_speed);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> GREATER_SEA_ATTUNEMENT_BUFF = Services.TEST_FUNCTIONS_REGISTRY.register("greater_sea_attunement_gives_water_breathing", () -> AttunementTests::greater_sea_attunement_gives_water_breathing);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> LESSER_SKY_ATTUNEMENT_BUFF1 = Services.TEST_FUNCTIONS_REGISTRY.register("lesser_sky_attunement_gives_movement_speed_modifier", () -> AttunementTests::lesser_sky_attunement_gives_movement_speed_modifier);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> LESSER_SKY_ATTUNEMENT_BUFF2 = Services.TEST_FUNCTIONS_REGISTRY.register("lesser_sky_attunement_reduces_fall_damage_taken", () -> AttunementTests::lesser_sky_attunement_reduces_fall_damage_taken);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> GREATER_SKY_ATTUNEMENT_BUFF = Services.TEST_FUNCTIONS_REGISTRY.register("greater_sky_attunement_increases_jump_strength", () -> AttunementTests::greater_sky_attunement_increases_jump_strength);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> LESSER_SUN_ATTUNEMENT_DAY_BUFF = Services.TEST_FUNCTIONS_REGISTRY.register("lesser_sun_attunement_regenerates_food_during_day", () -> AttunementTests::lesser_sun_attunement_regenerates_food_during_day);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> LESSER_SUN_ATTUNEMENT_NIGHT_BUFF = Services.TEST_FUNCTIONS_REGISTRY.register("lesser_sun_attunement_does_not_regenerate_food_during_night", () -> AttunementTests::lesser_sun_attunement_does_not_regenerate_food_during_night);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> LESSER_MOON_ATTUNEMENT_BUFF = Services.TEST_FUNCTIONS_REGISTRY.register("lesser_moon_attunement_grants_invisibility_chance_on_hurt", () -> AttunementTests::lesser_moon_attunement_grants_invisibility_chance_on_hurt);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> GREATER_MOON_ATTUNEMENT_BUFF = Services.TEST_FUNCTIONS_REGISTRY.register("greater_moon_attunement_grants_night_vision", () -> AttunementTests::greater_moon_attunement_grants_night_vision);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> LESSER_BLOOD_ATTUNEMENT_BUFF = Services.TEST_FUNCTIONS_REGISTRY.register("lesser_blood_attunement_inflicts_bleeding", () -> AttunementTests::lesser_blood_attunement_inflicts_bleeding);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> GREATER_BLOOD_ATTUNEMENT_BUFF = Services.TEST_FUNCTIONS_REGISTRY.register("greater_blood_attunement_grants_chance_at_self_healing", () -> AttunementTests::greater_blood_attunement_grants_chance_at_self_healing);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> GREATER_INFERNAL_ATTUNEMENT_BUFF_IN_FIRE = Services.TEST_FUNCTIONS_REGISTRY.register("greater_infernal_attunement_prevents_fire_damage_in_fire", () -> (helper) -> AttunementTests.greater_infernal_attunement_prevents_fire_damage(helper, registryAccess -> new DamageSources(registryAccess).inFire()));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> GREATER_INFERNAL_ATTUNEMENT_BUFF_ON_FIRE = Services.TEST_FUNCTIONS_REGISTRY.register("greater_infernal_attunement_prevents_fire_damage_on_fire", () -> (helper) -> AttunementTests.greater_infernal_attunement_prevents_fire_damage(helper, registryAccess -> new DamageSources(registryAccess).onFire()));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> GREATER_INFERNAL_ATTUNEMENT_BUFF_LAVA = Services.TEST_FUNCTIONS_REGISTRY.register("greater_infernal_attunement_prevents_fire_damage_lava", () -> (helper) -> AttunementTests.greater_infernal_attunement_prevents_fire_damage(helper, registryAccess -> new DamageSources(registryAccess).lava()));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> GREATER_INFERNAL_ATTUNEMENT_BUFF_HOT_FLOOR = Services.TEST_FUNCTIONS_REGISTRY.register("greater_infernal_attunement_prevents_fire_damage_hot_floor", () -> (helper) -> AttunementTests.greater_infernal_attunement_prevents_fire_damage(helper, registryAccess -> new DamageSources(registryAccess).hotFloor()));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> GREATER_INFERNAL_ATTUNEMENT_BUFF_INFERNAL_SORCERY = Services.TEST_FUNCTIONS_REGISTRY.register("greater_infernal_attunement_prevents_fire_damage_infernal_sorcery", () -> (helper) -> AttunementTests.greater_infernal_attunement_prevents_fire_damage(helper, registryAccess -> DamageSourcesPM.sorcery(registryAccess, Sources.INFERNAL, null)));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> LESSER_VOID_ATTUNEMENT_BUFF = Services.TEST_FUNCTIONS_REGISTRY.register("lesser_void_attunement_reduces_damage_taken", () -> AttunementTests::lesser_void_attunement_reduces_damage_taken);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> GREATER_VOID_ATTUNEMENT_BUFF = Services.TEST_FUNCTIONS_REGISTRY.register("greater_void_attunement_increases_damage_dealt", () -> AttunementTests::greater_void_attunement_increases_damage_dealt);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> LESSER_HALLOWED_ATTUNEMENT_BUFF = Services.TEST_FUNCTIONS_REGISTRY.register("lesser_hallowed_attunement_doubles_damage_dealt_to_undead", () -> AttunementTests::lesser_hallowed_attunement_doubles_damage_dealt_to_undead);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> GREATER_HALLOWED_ATTUNEMENT_BUFF = Services.TEST_FUNCTIONS_REGISTRY.register("greater_hallowed_attunement_prevents_death", () -> AttunementTests::greater_hallowed_attunement_prevents_death);

    // Item handler tests
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> ITEM_HANDLER_NULL_DIRECTION_RESEARCH_TABLE = Services.TEST_FUNCTIONS_REGISTRY.register("block_entity_can_retrieve_item_handler_with_null_direction_research_table", () -> (helper) -> ItemHandlerTests.block_entity_can_retrieve_item_handler_with_null_direction(helper, BlocksPM.RESEARCH_TABLE.get()));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> ITEM_HANDLER_NULL_DIRECTION_WAND_CHARGER = Services.TEST_FUNCTIONS_REGISTRY.register("block_entity_can_retrieve_item_handler_with_null_direction_wand_charger", () -> (helper) -> ItemHandlerTests.block_entity_can_retrieve_item_handler_with_null_direction(helper, BlocksPM.WAND_CHARGER.get()));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> ITEM_HANDLER_NULL_DIRECTION_CALCINATOR_BASIC = Services.TEST_FUNCTIONS_REGISTRY.register("block_entity_can_retrieve_item_handler_with_null_direction_calcinator_basic", () -> (helper) -> ItemHandlerTests.block_entity_can_retrieve_item_handler_with_null_direction(helper, BlocksPM.CALCINATOR_BASIC.get()));

    // Player knowledge tests
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> ADD_AND_CHECK_RESEARCH = Services.TEST_FUNCTIONS_REGISTRY.register("player_knowledge_add_and_check_research", () -> PlayerKnowledgeTests::player_knowledge_add_and_check_research);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> CANNOT_ADD_DUPLICATE_RESEARCH = Services.TEST_FUNCTIONS_REGISTRY.register("player_knowledge_cannot_add_duplicate_research", () -> PlayerKnowledgeTests::player_knowledge_cannot_add_duplicate_research);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> REMOVE_RESEARCH = Services.TEST_FUNCTIONS_REGISTRY.register("player_knowledge_remove_research", () -> PlayerKnowledgeTests::player_knowledge_remove_research);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> GET_RESEARCH_SET = Services.TEST_FUNCTIONS_REGISTRY.register("player_knowledge_get_research_set", () -> PlayerKnowledgeTests::player_knowledge_get_research_set);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> GET_SET_RESEARCH_STAGE = Services.TEST_FUNCTIONS_REGISTRY.register("player_knowledge_get_set_research_stage", () -> PlayerKnowledgeTests::player_knowledge_get_set_research_stage);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> GET_SET_RESEARCH_FLAG = Services.TEST_FUNCTIONS_REGISTRY.register("player_knowledge_get_set_research_flag", () -> PlayerKnowledgeTests::player_knowledge_get_set_research_flag);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> REMOVE_RESEARCH_FLAG = Services.TEST_FUNCTIONS_REGISTRY.register("player_knowledge_remove_research_flag", () -> PlayerKnowledgeTests::player_knowledge_remove_research_flag);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> GET_RESEARCH_FLAGS = Services.TEST_FUNCTIONS_REGISTRY.register("player_knowledge_get_research_flags", () -> PlayerKnowledgeTests::player_knowledge_get_research_flags);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> GET_RESEARCH_STATUS = Services.TEST_FUNCTIONS_REGISTRY.register("player_knowledge_get_research_status", () -> PlayerKnowledgeTests::player_knowledge_get_research_status);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> IS_RESEARCH_COMPLETE = Services.TEST_FUNCTIONS_REGISTRY.register("player_knowledge_is_research_complete", () -> PlayerKnowledgeTests::player_knowledge_is_research_complete);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> GET_SET_KNOWLEDGE_RAW = Services.TEST_FUNCTIONS_REGISTRY.register("player_knowledge_get_set_knowledge_raw", () -> PlayerKnowledgeTests::player_knowledge_get_set_knowledge_raw);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> GET_KNOWLEDGE_LEVELS = Services.TEST_FUNCTIONS_REGISTRY.register("player_knowledge_get_knowledge_levels", () -> PlayerKnowledgeTests::player_knowledge_get_knowledge_levels);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> GET_SET_ACTIVE_RESEARCH_PROJECT = Services.TEST_FUNCTIONS_REGISTRY.register("player_knowledge_get_set_active_research_project", () -> PlayerKnowledgeTests::player_knowledge_get_set_active_research_project);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> GET_SET_LAST_RESEARCH_TOPIC = Services.TEST_FUNCTIONS_REGISTRY.register("player_knowledge_get_set_last_research_topic", () -> PlayerKnowledgeTests::player_knowledge_get_set_last_research_topic);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> GET_SET_RESEARCH_TOPIC_HISTORY = Services.TEST_FUNCTIONS_REGISTRY.register("player_knowledge_get_set_research_topic_history", () -> PlayerKnowledgeTests::player_knowledge_get_set_research_topic_history);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> KNOWLEDGE_SERIALIZATION = Services.TEST_FUNCTIONS_REGISTRY.register("player_knowledge_serialization", () -> PlayerKnowledgeTests::player_knowledge_serialization);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> ADD_AND_CHECK_RESEARCH_POST_SERIALIZATION = Services.TEST_FUNCTIONS_REGISTRY.register("player_knowledge_add_and_check_research_post_serialization", () -> PlayerKnowledgeTests::player_knowledge_add_and_check_research_post_serialization);

    // Arcane workbench tests
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> ARCANE_WORKBENCH_CRAFT_WORKS = Services.TEST_FUNCTIONS_REGISTRY.register("arcane_workbench_craft_works", () -> ArcaneWorkbenchTests::arcane_workbench_craft_works);

    // Calcinator tests
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> CALCINATOR_WORKS_WITH_PLAYER_PRESENT = Services.TEST_FUNCTIONS_REGISTRY.register("calcinator_works_with_player_present", () -> (helper) -> CalcinatorTests.calcinator_works(helper, true));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> CALCINATOR_WORKS_WITHOUT_PLAYER_PRESENT = Services.TEST_FUNCTIONS_REGISTRY.register("calcinator_works_without_player_present", () -> (helper) -> CalcinatorTests.calcinator_works(helper, false));

    // Crafting requirement tests
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> CRAFTING_REQUIREMENT_ARCANE_RECIPE = Services.TEST_FUNCTIONS_REGISTRY.register("crafting_requirement_arcane_recipe", () -> CraftingRequirementsTests::arcane_recipe);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> CRAFTING_REQUIREMENT_RITUAL_RECIPE = Services.TEST_FUNCTIONS_REGISTRY.register("crafting_requirement_ritual_recipe", () -> CraftingRequirementsTests::ritual_recipe);

    // Repair tests
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> EARTHSHATTER_HAMMER_CANNOT_BE_REPAIRED = Services.TEST_FUNCTIONS_REGISTRY.register("earthshatter_hammer_cannot_be_repaired", () -> RepairTests::earthshatter_hammer_cannot_be_repaired);

    // Runecarving tests
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> RUNECARVING_CRAFT_WORKS = Services.TEST_FUNCTIONS_REGISTRY.register("runecarving_craft_works", () -> RunecarvingTests::craft_works);

    // Caster enchanting tests
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> CASTER_ENCHANTABLE_MUNDANE_WAND = Services.TEST_FUNCTIONS_REGISTRY.register("caster_enchantable_mundane_wand", () -> (helper) -> CasterEnchantingTests.caster_can_be_enchanted(helper, ItemsPM.MUNDANE_WAND.get()));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> CASTER_ENCHANTABLE_MODULAR_WAND = Services.TEST_FUNCTIONS_REGISTRY.register("caster_enchantable_modular_wand", () -> (helper) -> CasterEnchantingTests.caster_can_be_enchanted(helper, ItemsPM.MODULAR_WAND.get()));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> CASTER_ENCHANTABLE_MODULAR_STAFF = Services.TEST_FUNCTIONS_REGISTRY.register("caster_enchantable_modular_staff", () -> (helper) -> CasterEnchantingTests.caster_can_be_enchanted(helper, ItemsPM.MODULAR_STAFF.get()));

    // Ritual enchantment tests
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> ENCHANTMENT_ESSENCE_THIEF1 = Services.TEST_FUNCTIONS_REGISTRY.register("enchantment_essence_thief1", () -> (helper) -> RitualEnchantmentTests.enchantment_essence_thief(helper, 1));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> ENCHANTMENT_ESSENCE_THIEF2 = Services.TEST_FUNCTIONS_REGISTRY.register("enchantment_essence_thief2", () -> (helper) -> RitualEnchantmentTests.enchantment_essence_thief(helper, 2));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> ENCHANTMENT_ESSENCE_THIEF3 = Services.TEST_FUNCTIONS_REGISTRY.register("enchantment_essence_thief3", () -> (helper) -> RitualEnchantmentTests.enchantment_essence_thief(helper, 3));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> ENCHANTMENT_ESSENCE_THIEF4 = Services.TEST_FUNCTIONS_REGISTRY.register("enchantment_essence_thief4", () -> (helper) -> RitualEnchantmentTests.enchantment_essence_thief(helper, 4));

    // FTUX tests
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> FONT_DISCOVERY_EARTH = Services.TEST_FUNCTIONS_REGISTRY.register("font_discovery_earth", () -> (helper) -> FtuxTests.font_discovery(helper, BlocksPM.ANCIENT_FONT_EARTH.get()));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> FONT_DISCOVERY_SEA = Services.TEST_FUNCTIONS_REGISTRY.register("font_discovery_sea", () -> (helper) -> FtuxTests.font_discovery(helper, BlocksPM.ANCIENT_FONT_SEA.get()));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> FONT_DISCOVERY_SKY = Services.TEST_FUNCTIONS_REGISTRY.register("font_discovery_sky", () -> (helper) -> FtuxTests.font_discovery(helper, BlocksPM.ANCIENT_FONT_SKY.get()));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> FONT_DISCOVERY_SUN = Services.TEST_FUNCTIONS_REGISTRY.register("font_discovery_sun", () -> (helper) -> FtuxTests.font_discovery(helper, BlocksPM.ANCIENT_FONT_SUN.get()));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> FONT_DISCOVERY_MOON = Services.TEST_FUNCTIONS_REGISTRY.register("font_discovery_moon", () -> (helper) -> FtuxTests.font_discovery(helper, BlocksPM.ANCIENT_FONT_MOON.get()));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> SLEEP_AFTER_SHRINE_GRANTS_DREAM = Services.TEST_FUNCTIONS_REGISTRY.register("sleeping_after_shrine_grants_dream", () -> FtuxTests::sleeping_after_shrine_grants_dream);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> MUNDANE_WAND_CRAFTING_EARTH = Services.TEST_FUNCTIONS_REGISTRY.register("mundane_wand_crafting_earth", () -> (helper) -> FtuxTests.mundane_wand_crafting(helper, ItemsPM.ESSENCE_DUST_EARTH.get()));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> MUNDANE_WAND_CRAFTING_SEA = Services.TEST_FUNCTIONS_REGISTRY.register("mundane_wand_crafting_sea", () -> (helper) -> FtuxTests.mundane_wand_crafting(helper, ItemsPM.ESSENCE_DUST_SEA.get()));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> MUNDANE_WAND_CRAFTING_SKY = Services.TEST_FUNCTIONS_REGISTRY.register("mundane_wand_crafting_sky", () -> (helper) -> FtuxTests.mundane_wand_crafting(helper, ItemsPM.ESSENCE_DUST_SKY.get()));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> MUNDANE_WAND_CRAFTING_SUN = Services.TEST_FUNCTIONS_REGISTRY.register("mundane_wand_crafting_sun", () -> (helper) -> FtuxTests.mundane_wand_crafting(helper, ItemsPM.ESSENCE_DUST_SUN.get()));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> MUNDANE_WAND_CRAFTING_MOON = Services.TEST_FUNCTIONS_REGISTRY.register("mundane_wand_crafting_moon", () -> (helper) -> FtuxTests.mundane_wand_crafting(helper, ItemsPM.ESSENCE_DUST_MOON.get()));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> TRANSFORM_ABORT_GIVES_HINT = Services.TEST_FUNCTIONS_REGISTRY.register("transform_abort_gives_hint", () -> FtuxTests::transform_abort_gives_hint);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> TRANSFORM_WITHOUT_DREAM_DOES_NOTHING = Services.TEST_FUNCTIONS_REGISTRY.register("transform_without_dream_does_nothing", () -> FtuxTests::transform_without_dream_does_nothing);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> TRANSFORM_GRIMOIRE = Services.TEST_FUNCTIONS_REGISTRY.register("transform_grimoire", () -> FtuxTests::transform_grimoire);

    // Beeswax item tests
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> APPLY_BEESWAX_DIRECTLY_CLEAN = Services.TEST_FUNCTIONS_REGISTRY.register("apply_beeswax_directly_clean", () -> (helper) -> BeeswaxTests.apply_beeswax_directly(helper, Blocks.COPPER_BLOCK, Blocks.WAXED_COPPER_BLOCK));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> APPLY_BEESWAX_DIRECTLY_EXPOSED = Services.TEST_FUNCTIONS_REGISTRY.register("apply_beeswax_directly_exposed", () -> (helper) -> BeeswaxTests.apply_beeswax_directly(helper, Blocks.EXPOSED_COPPER, Blocks.WAXED_EXPOSED_COPPER));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> APPLY_BEESWAX_DIRECTLY_WEATHERED = Services.TEST_FUNCTIONS_REGISTRY.register("apply_beeswax_directly_weathered", () -> (helper) -> BeeswaxTests.apply_beeswax_directly(helper, Blocks.WEATHERED_COPPER, Blocks.WAXED_WEATHERED_COPPER));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> APPLY_BEESWAX_DIRECTLY_OXIDIZED = Services.TEST_FUNCTIONS_REGISTRY.register("apply_beeswax_directly_oxidized", () -> (helper) -> BeeswaxTests.apply_beeswax_directly(helper, Blocks.OXIDIZED_COPPER, Blocks.WAXED_OXIDIZED_COPPER));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> APPLY_BEESWAX_VIA_CRAFTING_CLEAN = Services.TEST_FUNCTIONS_REGISTRY.register("apply_beeswax_via_crafting_clean", () -> (helper) -> BeeswaxTests.apply_beeswax_via_crafting(helper, Blocks.COPPER_BLOCK, Blocks.WAXED_COPPER_BLOCK));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> APPLY_BEESWAX_VIA_CRAFTING_EXPOSED = Services.TEST_FUNCTIONS_REGISTRY.register("apply_beeswax_via_crafting_exposed", () -> (helper) -> BeeswaxTests.apply_beeswax_via_crafting(helper, Blocks.EXPOSED_COPPER, Blocks.WAXED_EXPOSED_COPPER));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> APPLY_BEESWAX_VIA_CRAFTING_WEATHERED = Services.TEST_FUNCTIONS_REGISTRY.register("apply_beeswax_via_crafting_weathered", () -> (helper) -> BeeswaxTests.apply_beeswax_via_crafting(helper, Blocks.WEATHERED_COPPER, Blocks.WAXED_WEATHERED_COPPER));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> APPLY_BEESWAX_VIA_CRAFTING_OXIDIZED = Services.TEST_FUNCTIONS_REGISTRY.register("apply_beeswax_via_crafting_oxidized", () -> (helper) -> BeeswaxTests.apply_beeswax_via_crafting(helper, Blocks.OXIDIZED_COPPER, Blocks.WAXED_OXIDIZED_COPPER));

    // Dispenser item tests
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> MANA_ARROWS_FIRED_FROM_DISPENSER_EARTH = Services.TEST_FUNCTIONS_REGISTRY.register("mana_arrows_fired_from_dispenser_earth", () -> (helper) -> DispenserTests.mana_arrows_fired_from_dispenser(helper, ItemsPM.MANA_ARROW_EARTH.get()));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> MANA_ARROWS_FIRED_FROM_DISPENSER_SEA = Services.TEST_FUNCTIONS_REGISTRY.register("mana_arrows_fired_from_dispenser_sea", () -> (helper) -> DispenserTests.mana_arrows_fired_from_dispenser(helper, ItemsPM.MANA_ARROW_SEA.get()));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> MANA_ARROWS_FIRED_FROM_DISPENSER_SKY = Services.TEST_FUNCTIONS_REGISTRY.register("mana_arrows_fired_from_dispenser_sky", () -> (helper) -> DispenserTests.mana_arrows_fired_from_dispenser(helper, ItemsPM.MANA_ARROW_SKY.get()));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> MANA_ARROWS_FIRED_FROM_DISPENSER_SUN = Services.TEST_FUNCTIONS_REGISTRY.register("mana_arrows_fired_from_dispenser_sun", () -> (helper) -> DispenserTests.mana_arrows_fired_from_dispenser(helper, ItemsPM.MANA_ARROW_SUN.get()));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> MANA_ARROWS_FIRED_FROM_DISPENSER_MOON = Services.TEST_FUNCTIONS_REGISTRY.register("mana_arrows_fired_from_dispenser_moon", () -> (helper) -> DispenserTests.mana_arrows_fired_from_dispenser(helper, ItemsPM.MANA_ARROW_MOON.get()));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> MANA_ARROWS_FIRED_FROM_DISPENSER_BLOOD = Services.TEST_FUNCTIONS_REGISTRY.register("mana_arrows_fired_from_dispenser_blood", () -> (helper) -> DispenserTests.mana_arrows_fired_from_dispenser(helper, ItemsPM.MANA_ARROW_BLOOD.get()));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> MANA_ARROWS_FIRED_FROM_DISPENSER_INFERNAL = Services.TEST_FUNCTIONS_REGISTRY.register("mana_arrows_fired_from_dispenser_infernal", () -> (helper) -> DispenserTests.mana_arrows_fired_from_dispenser(helper, ItemsPM.MANA_ARROW_INFERNAL.get()));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> MANA_ARROWS_FIRED_FROM_DISPENSER_VOID = Services.TEST_FUNCTIONS_REGISTRY.register("mana_arrows_fired_from_dispenser_void", () -> (helper) -> DispenserTests.mana_arrows_fired_from_dispenser(helper, ItemsPM.MANA_ARROW_VOID.get()));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> MANA_ARROWS_FIRED_FROM_DISPENSER_HALLOWED = Services.TEST_FUNCTIONS_REGISTRY.register("mana_arrows_fired_from_dispenser_hallowed", () -> (helper) -> DispenserTests.mana_arrows_fired_from_dispenser(helper, ItemsPM.MANA_ARROW_HALLOWED.get()));

    // Wand mana tests
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CAN_GET_AND_ADD_MANA = Services.TEST_FUNCTIONS_REGISTRY.register("wand_can_get_and_add_mana", () -> (helper) -> WandManaTests.wand_can_get_and_add_mana(helper, Sources.EARTH));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CAN_GET_AND_ADD_REAL_MANA = Services.TEST_FUNCTIONS_REGISTRY.register("wand_can_get_and_add_real_mana", () -> WandManaTests::wand_can_get_and_add_real_mana);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CANNOT_ADD_TOO_MUCH_MANA = Services.TEST_FUNCTIONS_REGISTRY.register("wand_cannot_add_too_much_mana", () -> (helper) -> WandManaTests.wand_cannot_add_too_much_mana(helper, Sources.EARTH));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CAN_GET_ALL_MANA = Services.TEST_FUNCTIONS_REGISTRY.register("wand_can_get_all_mana", () -> WandManaTests::wand_can_get_all_mana);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CAN_CONSUME_MANA = Services.TEST_FUNCTIONS_REGISTRY.register("wand_can_consume_mana", () -> (helper) -> WandManaTests.wand_can_consume_mana(helper, Sources.EARTH));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CANNOT_CONSUME_MORE_MANA_THAN_IT_HAS = Services.TEST_FUNCTIONS_REGISTRY.register("wand_cannot_consume_more_mana_than_it_has", () -> (helper) -> WandManaTests.wand_cannot_consume_more_mana_than_it_has(helper, Sources.EARTH));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CAN_CONSUME_MULTIPLE_TYPES_OF_MANA = Services.TEST_FUNCTIONS_REGISTRY.register("wand_can_consume_multiple_types_of_mana", () -> WandManaTests::wand_can_consume_multiple_types_of_mana);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CANNOT_CONSUME_MORE_MANA_THAN_IT_HAS_WITH_MULTIPLE_TYPES = Services.TEST_FUNCTIONS_REGISTRY.register("wand_cannot_consume_more_mana_than_it_has_with_multiple_types", () -> WandManaTests::wand_cannot_consume_more_mana_than_it_has_with_multiple_types);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CAN_REMOVE_MANA_RAW = Services.TEST_FUNCTIONS_REGISTRY.register("wand_can_remove_mana_raw", () -> WandManaTests::wand_can_remove_mana_raw);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CANNOT_REMOVE_MORE_RAW_MANA_THAN_IT_HAS = Services.TEST_FUNCTIONS_REGISTRY.register("wand_cannot_remove_more_raw_mana_than_it_has", () -> WandManaTests::wand_cannot_remove_more_raw_mana_than_it_has);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CONTAINS_MANA = Services.TEST_FUNCTIONS_REGISTRY.register("wand_contains_mana", () -> WandManaTests::wand_contains_mana);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CONTAINS_MANA_LIST = Services.TEST_FUNCTIONS_REGISTRY.register("wand_contains_mana_list", () -> WandManaTests::wand_contains_mana_list);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CONTAINS_MANA_RAW = Services.TEST_FUNCTIONS_REGISTRY.register("wand_contains_mana_raw", () -> WandManaTests::wand_contains_mana_raw);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CAN_GET_AND_ADD_MANA_SEA = Services.TEST_FUNCTIONS_REGISTRY.register("wand_can_get_and_add_mana_sea", () -> (helper) -> WandManaTests.wand_can_get_and_add_mana(helper, Sources.SEA));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CAN_GET_AND_ADD_MANA_SKY = Services.TEST_FUNCTIONS_REGISTRY.register("wand_can_get_and_add_mana_sky", () -> (helper) -> WandManaTests.wand_can_get_and_add_mana(helper, Sources.SKY));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CAN_GET_AND_ADD_MANA_SUN = Services.TEST_FUNCTIONS_REGISTRY.register("wand_can_get_and_add_mana_sun", () -> (helper) -> WandManaTests.wand_can_get_and_add_mana(helper, Sources.SUN));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CAN_GET_AND_ADD_MANA_MOON = Services.TEST_FUNCTIONS_REGISTRY.register("wand_can_get_and_add_mana_moon", () -> (helper) -> WandManaTests.wand_can_get_and_add_mana(helper, Sources.MOON));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CAN_GET_AND_ADD_MANA_BLOOD = Services.TEST_FUNCTIONS_REGISTRY.register("wand_can_get_and_add_mana_blood", () -> (helper) -> WandManaTests.wand_can_get_and_add_mana(helper, Sources.BLOOD));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CAN_GET_AND_ADD_MANA_INFERNAL = Services.TEST_FUNCTIONS_REGISTRY.register("wand_can_get_and_add_mana_infernal", () -> (helper) -> WandManaTests.wand_can_get_and_add_mana(helper, Sources.INFERNAL));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CAN_GET_AND_ADD_MANA_VOID = Services.TEST_FUNCTIONS_REGISTRY.register("wand_can_get_and_add_mana_void", () -> (helper) -> WandManaTests.wand_can_get_and_add_mana(helper, Sources.VOID));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CAN_GET_AND_ADD_MANA_HALLOWED = Services.TEST_FUNCTIONS_REGISTRY.register("wand_can_get_and_add_mana_hallowed", () -> (helper) -> WandManaTests.wand_can_get_and_add_mana(helper, Sources.HALLOWED));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CANNOT_ADD_TOO_MUCH_MANA_SEA = Services.TEST_FUNCTIONS_REGISTRY.register("wand_cannot_add_too_much_mana_sea", () -> (helper) -> WandManaTests.wand_cannot_add_too_much_mana(helper, Sources.SEA));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CANNOT_ADD_TOO_MUCH_MANA_SKY = Services.TEST_FUNCTIONS_REGISTRY.register("wand_cannot_add_too_much_mana_sky", () -> (helper) -> WandManaTests.wand_cannot_add_too_much_mana(helper, Sources.SKY));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CANNOT_ADD_TOO_MUCH_MANA_SUN = Services.TEST_FUNCTIONS_REGISTRY.register("wand_cannot_add_too_much_mana_sun", () -> (helper) -> WandManaTests.wand_cannot_add_too_much_mana(helper, Sources.SUN));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CANNOT_ADD_TOO_MUCH_MANA_MOON = Services.TEST_FUNCTIONS_REGISTRY.register("wand_cannot_add_too_much_mana_moon", () -> (helper) -> WandManaTests.wand_cannot_add_too_much_mana(helper, Sources.MOON));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CANNOT_ADD_TOO_MUCH_MANA_BLOOD = Services.TEST_FUNCTIONS_REGISTRY.register("wand_cannot_add_too_much_mana_blood", () -> (helper) -> WandManaTests.wand_cannot_add_too_much_mana(helper, Sources.BLOOD));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CANNOT_ADD_TOO_MUCH_MANA_INFERNAL = Services.TEST_FUNCTIONS_REGISTRY.register("wand_cannot_add_too_much_mana_infernal", () -> (helper) -> WandManaTests.wand_cannot_add_too_much_mana(helper, Sources.INFERNAL));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CANNOT_ADD_TOO_MUCH_MANA_VOID = Services.TEST_FUNCTIONS_REGISTRY.register("wand_cannot_add_too_much_mana_void", () -> (helper) -> WandManaTests.wand_cannot_add_too_much_mana(helper, Sources.VOID));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CANNOT_ADD_TOO_MUCH_MANA_HALLOWED = Services.TEST_FUNCTIONS_REGISTRY.register("wand_cannot_add_too_much_mana_hallowed", () -> (helper) -> WandManaTests.wand_cannot_add_too_much_mana(helper, Sources.HALLOWED));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CAN_CONSUME_MANA_SEA = Services.TEST_FUNCTIONS_REGISTRY.register("wand_can_consume_mana_sea", () -> (helper) -> WandManaTests.wand_can_consume_mana(helper, Sources.SEA));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CAN_CONSUME_MANA_SKY = Services.TEST_FUNCTIONS_REGISTRY.register("wand_can_consume_mana_sky", () -> (helper) -> WandManaTests.wand_can_consume_mana(helper, Sources.SKY));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CAN_CONSUME_MANA_SUN = Services.TEST_FUNCTIONS_REGISTRY.register("wand_can_consume_mana_sun", () -> (helper) -> WandManaTests.wand_can_consume_mana(helper, Sources.SUN));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CAN_CONSUME_MANA_MOON = Services.TEST_FUNCTIONS_REGISTRY.register("wand_can_consume_mana_moon", () -> (helper) -> WandManaTests.wand_can_consume_mana(helper, Sources.MOON));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CAN_CONSUME_MANA_BLOOD = Services.TEST_FUNCTIONS_REGISTRY.register("wand_can_consume_mana_blood", () -> (helper) -> WandManaTests.wand_can_consume_mana(helper, Sources.BLOOD));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CAN_CONSUME_MANA_INFERNAL = Services.TEST_FUNCTIONS_REGISTRY.register("wand_can_consume_mana_infernal", () -> (helper) -> WandManaTests.wand_can_consume_mana(helper, Sources.INFERNAL));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CAN_CONSUME_MANA_VOID = Services.TEST_FUNCTIONS_REGISTRY.register("wand_can_consume_mana_void", () -> (helper) -> WandManaTests.wand_can_consume_mana(helper, Sources.VOID));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CAN_CONSUME_MANA_HALLOWED = Services.TEST_FUNCTIONS_REGISTRY.register("wand_can_consume_mana_hallowed", () -> (helper) -> WandManaTests.wand_can_consume_mana(helper, Sources.HALLOWED));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CANNOT_CONSUME_MORE_MANA_THAN_IT_HAS_SEA = Services.TEST_FUNCTIONS_REGISTRY.register("wand_cannot_consume_more_mana_than_it_has_sea", () -> (helper) -> WandManaTests.wand_cannot_consume_more_mana_than_it_has(helper, Sources.SEA));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CANNOT_CONSUME_MORE_MANA_THAN_IT_HAS_SKY = Services.TEST_FUNCTIONS_REGISTRY.register("wand_cannot_consume_more_mana_than_it_has_sky", () -> (helper) -> WandManaTests.wand_cannot_consume_more_mana_than_it_has(helper, Sources.SKY));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CANNOT_CONSUME_MORE_MANA_THAN_IT_HAS_SUN = Services.TEST_FUNCTIONS_REGISTRY.register("wand_cannot_consume_more_mana_than_it_has_sun", () -> (helper) -> WandManaTests.wand_cannot_consume_more_mana_than_it_has(helper, Sources.SUN));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CANNOT_CONSUME_MORE_MANA_THAN_IT_HAS_MOON = Services.TEST_FUNCTIONS_REGISTRY.register("wand_cannot_consume_more_mana_than_it_has_moon", () -> (helper) -> WandManaTests.wand_cannot_consume_more_mana_than_it_has(helper, Sources.MOON));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CANNOT_CONSUME_MORE_MANA_THAN_IT_HAS_BLOOD = Services.TEST_FUNCTIONS_REGISTRY.register("wand_cannot_consume_more_mana_than_it_has_blood", () -> (helper) -> WandManaTests.wand_cannot_consume_more_mana_than_it_has(helper, Sources.BLOOD));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CANNOT_CONSUME_MORE_MANA_THAN_IT_HAS_INFERNAL = Services.TEST_FUNCTIONS_REGISTRY.register("wand_cannot_consume_more_mana_than_it_has_infernal", () -> (helper) -> WandManaTests.wand_cannot_consume_more_mana_than_it_has(helper, Sources.INFERNAL));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CANNOT_CONSUME_MORE_MANA_THAN_IT_HAS_VOID = Services.TEST_FUNCTIONS_REGISTRY.register("wand_cannot_consume_more_mana_than_it_has_void", () -> (helper) -> WandManaTests.wand_cannot_consume_more_mana_than_it_has(helper, Sources.VOID));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CANNOT_CONSUME_MORE_MANA_THAN_IT_HAS_HALLOWED = Services.TEST_FUNCTIONS_REGISTRY.register("wand_cannot_consume_more_mana_than_it_has_hallowed", () -> (helper) -> WandManaTests.wand_cannot_consume_more_mana_than_it_has(helper, Sources.HALLOWED));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CAN_GET_AND_ADD_MANA_MUNDANE_WAND = Services.TEST_FUNCTIONS_REGISTRY.register("wand_can_get_and_add_mana_mundane_wand", () -> (helper) -> WandManaTests.wand_can_get_and_add_mana(helper, Sources.EARTH, WandManaTests.WandType.MUNDANE_WAND));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CAN_GET_AND_ADD_MANA_MODULAR_STAFF = Services.TEST_FUNCTIONS_REGISTRY.register("wand_can_get_and_add_mana_modular_staff", () -> (helper) -> WandManaTests.wand_can_get_and_add_mana(helper, Sources.EARTH, WandManaTests.WandType.MODULAR_STAFF));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CAN_CONSUME_MANA_MUNDANE_WAND = Services.TEST_FUNCTIONS_REGISTRY.register("wand_can_consume_mana_mundane_wand", () -> (helper) -> WandManaTests.wand_can_consume_mana(helper, Sources.EARTH, WandManaTests.WandType.MUNDANE_WAND));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CAN_CONSUME_MANA_MODULAR_STAFF = Services.TEST_FUNCTIONS_REGISTRY.register("wand_can_consume_mana_modular_staff", () -> (helper) -> WandManaTests.wand_can_consume_mana(helper, Sources.EARTH, WandManaTests.WandType.MODULAR_STAFF));

    // Wand component tests
    // Expected values below mirror the constants declared in WandGem, WandCap, and WandCore
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_GEM_SETS_MAX_MANA_APPRENTICE = Services.TEST_FUNCTIONS_REGISTRY.register("wand_gem_sets_max_mana_apprentice", () -> (helper) -> WandComponentTests.gem_sets_max_mana(helper, ItemsPM.MODULAR_WAND.get(), WandGem.APPRENTICE, 7500));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_GEM_SETS_MAX_MANA_ADEPT = Services.TEST_FUNCTIONS_REGISTRY.register("wand_gem_sets_max_mana_adept", () -> (helper) -> WandComponentTests.gem_sets_max_mana(helper, ItemsPM.MODULAR_WAND.get(), WandGem.ADEPT, 25000));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_GEM_SETS_MAX_MANA_WIZARD = Services.TEST_FUNCTIONS_REGISTRY.register("wand_gem_sets_max_mana_wizard", () -> (helper) -> WandComponentTests.gem_sets_max_mana(helper, ItemsPM.MODULAR_WAND.get(), WandGem.WIZARD, 75000));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_GEM_SETS_MAX_MANA_ARCHMAGE = Services.TEST_FUNCTIONS_REGISTRY.register("wand_gem_sets_max_mana_archmage", () -> (helper) -> WandComponentTests.gem_sets_max_mana(helper, ItemsPM.MODULAR_WAND.get(), WandGem.ARCHMAGE, 250000));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_GEM_CREATIVE_HAS_INFINITE_MANA = Services.TEST_FUNCTIONS_REGISTRY.register("wand_gem_creative_has_infinite_mana", () -> WandComponentTests::wand_gem_creative_has_infinite_mana);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CAP_SETS_BASE_COST_MODIFIER_IRON = Services.TEST_FUNCTIONS_REGISTRY.register("wand_cap_sets_base_cost_modifier_iron", () -> (helper) -> WandComponentTests.cap_sets_base_cost_modifier(helper, ItemsPM.MODULAR_WAND.get(), WandCap.IRON, 10));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CAP_SETS_BASE_COST_MODIFIER_GOLD = Services.TEST_FUNCTIONS_REGISTRY.register("wand_cap_sets_base_cost_modifier_gold", () -> (helper) -> WandComponentTests.cap_sets_base_cost_modifier(helper, ItemsPM.MODULAR_WAND.get(), WandCap.GOLD, 20));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CAP_SETS_BASE_COST_MODIFIER_PRIMALITE = Services.TEST_FUNCTIONS_REGISTRY.register("wand_cap_sets_base_cost_modifier_primalite", () -> (helper) -> WandComponentTests.cap_sets_base_cost_modifier(helper, ItemsPM.MODULAR_WAND.get(), WandCap.PRIMALITE, 25));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CAP_SETS_BASE_COST_MODIFIER_HEXIUM = Services.TEST_FUNCTIONS_REGISTRY.register("wand_cap_sets_base_cost_modifier_hexium", () -> (helper) -> WandComponentTests.cap_sets_base_cost_modifier(helper, ItemsPM.MODULAR_WAND.get(), WandCap.HEXIUM, 30));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CAP_SETS_BASE_COST_MODIFIER_HALLOWSTEEL = Services.TEST_FUNCTIONS_REGISTRY.register("wand_cap_sets_base_cost_modifier_hallowsteel", () -> (helper) -> WandComponentTests.cap_sets_base_cost_modifier(helper, ItemsPM.MODULAR_WAND.get(), WandCap.HALLOWSTEEL, 35));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CAP_SETS_SIPHON_AMOUNT_IRON = Services.TEST_FUNCTIONS_REGISTRY.register("wand_cap_sets_siphon_amount_iron", () -> (helper) -> WandComponentTests.cap_sets_siphon_amount(helper, ItemsPM.MODULAR_WAND.get(), WandCap.IRON, 100));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CAP_SETS_SIPHON_AMOUNT_GOLD = Services.TEST_FUNCTIONS_REGISTRY.register("wand_cap_sets_siphon_amount_gold", () -> (helper) -> WandComponentTests.cap_sets_siphon_amount(helper, ItemsPM.MODULAR_WAND.get(), WandCap.GOLD, 200));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CAP_SETS_SIPHON_AMOUNT_PRIMALITE = Services.TEST_FUNCTIONS_REGISTRY.register("wand_cap_sets_siphon_amount_primalite", () -> (helper) -> WandComponentTests.cap_sets_siphon_amount(helper, ItemsPM.MODULAR_WAND.get(), WandCap.PRIMALITE, 400));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CAP_SETS_SIPHON_AMOUNT_HEXIUM = Services.TEST_FUNCTIONS_REGISTRY.register("wand_cap_sets_siphon_amount_hexium", () -> (helper) -> WandComponentTests.cap_sets_siphon_amount(helper, ItemsPM.MODULAR_WAND.get(), WandCap.HEXIUM, 800));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CAP_SETS_SIPHON_AMOUNT_HALLOWSTEEL = Services.TEST_FUNCTIONS_REGISTRY.register("wand_cap_sets_siphon_amount_hallowsteel", () -> (helper) -> WandComponentTests.cap_sets_siphon_amount(helper, ItemsPM.MODULAR_WAND.get(), WandCap.HALLOWSTEEL, 1600));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CORE_SPELL_SLOTS_HEARTWOOD = Services.TEST_FUNCTIONS_REGISTRY.register("wand_core_spell_slots_heartwood", () -> (helper) -> WandComponentTests.core_spell_slots(helper, ItemsPM.MODULAR_WAND.get(), WandCore.HEARTWOOD, 1));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CORE_SPELL_SLOTS_OBSIDIAN = Services.TEST_FUNCTIONS_REGISTRY.register("wand_core_spell_slots_obsidian", () -> (helper) -> WandComponentTests.core_spell_slots(helper, ItemsPM.MODULAR_WAND.get(), WandCore.OBSIDIAN, 1));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CORE_SPELL_SLOTS_BONE = Services.TEST_FUNCTIONS_REGISTRY.register("wand_core_spell_slots_bone", () -> (helper) -> WandComponentTests.core_spell_slots(helper, ItemsPM.MODULAR_WAND.get(), WandCore.BONE, 2));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CORE_SPELL_SLOTS_PRIMAL = Services.TEST_FUNCTIONS_REGISTRY.register("wand_core_spell_slots_primal", () -> (helper) -> WandComponentTests.core_spell_slots(helper, ItemsPM.MODULAR_WAND.get(), WandCore.PRIMAL, 2));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CORE_SPELL_SLOTS_DARK_PRIMAL = Services.TEST_FUNCTIONS_REGISTRY.register("wand_core_spell_slots_dark_primal", () -> (helper) -> WandComponentTests.core_spell_slots(helper, ItemsPM.MODULAR_WAND.get(), WandCore.DARK_PRIMAL, 3));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CORE_SPELL_SLOTS_PURE_PRIMAL = Services.TEST_FUNCTIONS_REGISTRY.register("wand_core_spell_slots_pure_primal", () -> (helper) -> WandComponentTests.core_spell_slots(helper, ItemsPM.MODULAR_WAND.get(), WandCore.PURE_PRIMAL, 4));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CORE_BONUS_SLOT_ACCEPTS_MATCHING_SPELL_OBSIDIAN = Services.TEST_FUNCTIONS_REGISTRY.register("wand_core_bonus_slot_accepts_matching_spell_obsidian", () -> (helper) -> WandComponentTests.wand_core_bonus_slot_accepts_matching_spell(helper, WandCore.OBSIDIAN, EarthDamageSpellPayload.INSTANCE, 1));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CORE_BONUS_SLOT_ACCEPTS_MATCHING_SPELL_BONE = Services.TEST_FUNCTIONS_REGISTRY.register("wand_core_bonus_slot_accepts_matching_spell_bone", () -> (helper) -> WandComponentTests.wand_core_bonus_slot_accepts_matching_spell(helper, WandCore.BONE, BloodDamageSpellPayload.INSTANCE, 2));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CORE_ALIGNED_SOURCES_HEARTWOOD = Services.TEST_FUNCTIONS_REGISTRY.register("wand_core_aligned_sources_heartwood", () -> (helper) -> WandComponentTests.wand_core_aligned_sources(helper, WandCore.HEARTWOOD, Set.of()));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CORE_ALIGNED_SOURCES_BONE = Services.TEST_FUNCTIONS_REGISTRY.register("wand_core_aligned_sources_bone", () -> (helper) -> WandComponentTests.wand_core_aligned_sources(helper, WandCore.BONE, Set.of(Sources.BLOOD)));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CORE_ALIGNED_SOURCES_DARK_PRIMAL = Services.TEST_FUNCTIONS_REGISTRY.register("wand_core_aligned_sources_dark_primal", () -> (helper) -> WandComponentTests.wand_core_aligned_sources(helper, WandCore.DARK_PRIMAL, Set.of(Sources.EARTH, Sources.SEA, Sources.SKY, Sources.SUN, Sources.MOON, Sources.BLOOD, Sources.INFERNAL, Sources.VOID)));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> STAFF_GEM_SETS_MAX_MANA_WIZARD = Services.TEST_FUNCTIONS_REGISTRY.register("staff_gem_sets_max_mana_wizard", () -> (helper) -> WandComponentTests.gem_sets_max_mana(helper, ItemsPM.MODULAR_STAFF.get(), WandGem.WIZARD, 75000));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> STAFF_CAP_SETS_BASE_COST_MODIFIER_HEXIUM = Services.TEST_FUNCTIONS_REGISTRY.register("staff_cap_sets_base_cost_modifier_hexium", () -> (helper) -> WandComponentTests.cap_sets_base_cost_modifier(helper, ItemsPM.MODULAR_STAFF.get(), WandCap.HEXIUM, 30));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> STAFF_CAP_SETS_SIPHON_AMOUNT_HEXIUM = Services.TEST_FUNCTIONS_REGISTRY.register("staff_cap_sets_siphon_amount_hexium", () -> (helper) -> WandComponentTests.cap_sets_siphon_amount(helper, ItemsPM.MODULAR_STAFF.get(), WandCap.HEXIUM, 800));
    // Staves double the core's base spell slots, so the primal core's 2 become 4
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> STAFF_CORE_SPELL_SLOTS_PRIMAL = Services.TEST_FUNCTIONS_REGISTRY.register("staff_core_spell_slots_primal", () -> (helper) -> WandComponentTests.core_spell_slots(helper, ItemsPM.MODULAR_STAFF.get(), WandCore.PRIMAL, 4));

    // Research key tests
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> RESEARCH_KEY_DISCIPLINE = Services.TEST_FUNCTIONS_REGISTRY.register("research_key_discipline", () -> ResearchKeysTests::research_discipline);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> RESEARCH_KEY_ENTRY = Services.TEST_FUNCTIONS_REGISTRY.register("research_key_entry", () -> ResearchKeysTests::research_entry);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> RESEARCH_KEY_STAGE = Services.TEST_FUNCTIONS_REGISTRY.register("research_key_stage", () -> ResearchKeysTests::research_stage);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> RESEARCH_KEY_ITEM_SCAN = Services.TEST_FUNCTIONS_REGISTRY.register("research_key_item_scan", () -> ResearchKeysTests::item_scan);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> RESEARCH_KEY_ENTITY_SCAN = Services.TEST_FUNCTIONS_REGISTRY.register("research_key_entity_scan", () -> ResearchKeysTests::entity_scan);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> RESEARCH_KEY_STACK_CRAFTED = Services.TEST_FUNCTIONS_REGISTRY.register("research_key_stack_crafted", () -> ResearchKeysTests::stack_crafted);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> RESEARCH_KEY_TAG_CRAFTED = Services.TEST_FUNCTIONS_REGISTRY.register("research_key_tag_crafted", () -> ResearchKeysTests::tag_crafted);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> RESEARCH_KEY_RUNE_ENCHANTMENT = Services.TEST_FUNCTIONS_REGISTRY.register("research_key_rune_enchantment", () -> ResearchKeysTests::rune_enchantment);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> RESEARCH_KEY_RUNE_ENCHANTMENT_PARTIAL = Services.TEST_FUNCTIONS_REGISTRY.register("research_key_rune_enchantment_partial", () -> ResearchKeysTests::rune_enchantment_partial);

    // Research requirement tests
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> RESEARCH_REQUIREMENT_RESEARCH = Services.TEST_FUNCTIONS_REGISTRY.register("research_requirement_research", () -> ResearchRequirementsTests::research_requirement);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> RESEARCH_REQUIREMENT_KNOWLEDGE = Services.TEST_FUNCTIONS_REGISTRY.register("research_requirement_knowledge", () -> ResearchRequirementsTests::knowledge_requirement);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> RESEARCH_REQUIREMENT_ITEM_STACK = Services.TEST_FUNCTIONS_REGISTRY.register("research_requirement_item_stack", () -> ResearchRequirementsTests::item_stack_requirement);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> RESEARCH_REQUIREMENT_ITEM_TAG = Services.TEST_FUNCTIONS_REGISTRY.register("research_requirement_item_tag", () -> ResearchRequirementsTests::item_tag_requirement);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> RESEARCH_REQUIREMENT_STAT = Services.TEST_FUNCTIONS_REGISTRY.register("research_requirement_stat", () -> ResearchRequirementsTests::stat_requirement);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> RESEARCH_REQUIREMENT_EXPERTISE = Services.TEST_FUNCTIONS_REGISTRY.register("research_requirement_expertise", () -> ResearchRequirementsTests::expertise_requirement);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> RESEARCH_REQUIREMENT_VANILLA_ITEM_USED_STAT = Services.TEST_FUNCTIONS_REGISTRY.register("research_requirement_vanilla_item_used_stat", () -> ResearchRequirementsTests::vanilla_item_used_stat_requirement);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> RESEARCH_REQUIREMENT_VANILLA_CUSTOM_STAT = Services.TEST_FUNCTIONS_REGISTRY.register("research_requirement_vanilla_custom_stat", () -> ResearchRequirementsTests::vanilla_custom_stat_requirement);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> RESEARCH_REQUIREMENT_AND = Services.TEST_FUNCTIONS_REGISTRY.register("research_requirement_and", () -> ResearchRequirementsTests::and_requirement);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> RESEARCH_REQUIREMENT_OR = Services.TEST_FUNCTIONS_REGISTRY.register("research_requirement_or", () -> ResearchRequirementsTests::or_requirement);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> RESEARCH_REQUIREMENT_QUORUM = Services.TEST_FUNCTIONS_REGISTRY.register("research_requirement_quorum", () -> ResearchRequirementsTests::quorum_requirement);

    // Research system tests
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> RESEARCH_GRANT_WORKS = Services.TEST_FUNCTIONS_REGISTRY.register("research_grant_works", () -> ResearchTests::research_grant_works);

    // Spell tests
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> DAMAGE_SPELLS_WORK_EARTH = Services.TEST_FUNCTIONS_REGISTRY.register("damage_spells_work_earth", () -> (helper) -> WandSpellcastTests.damage_spells_deduct_mana_from_wand_and_award_expertise(helper, SpellPayloadsPM.EARTH_DAMAGE.get()));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> DAMAGE_SPELLS_WORK_SEA = Services.TEST_FUNCTIONS_REGISTRY.register("damage_spells_work_sea", () -> (helper) -> WandSpellcastTests.damage_spells_deduct_mana_from_wand_and_award_expertise(helper, SpellPayloadsPM.FROST_DAMAGE.get()));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> DAMAGE_SPELLS_WORK_SKY = Services.TEST_FUNCTIONS_REGISTRY.register("damage_spells_work_sky", () -> (helper) -> WandSpellcastTests.damage_spells_deduct_mana_from_wand_and_award_expertise(helper, SpellPayloadsPM.LIGHTNING_DAMAGE.get()));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> DAMAGE_SPELLS_WORK_SUN = Services.TEST_FUNCTIONS_REGISTRY.register("damage_spells_work_sun", () -> (helper) -> WandSpellcastTests.damage_spells_deduct_mana_from_wand_and_award_expertise(helper, SpellPayloadsPM.SOLAR_DAMAGE.get()));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> DAMAGE_SPELLS_WORK_MOON = Services.TEST_FUNCTIONS_REGISTRY.register("damage_spells_work_moon", () -> (helper) -> WandSpellcastTests.damage_spells_deduct_mana_from_wand_and_award_expertise(helper, SpellPayloadsPM.LUNAR_DAMAGE.get()));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> DAMAGE_SPELLS_WORK_BLOOD = Services.TEST_FUNCTIONS_REGISTRY.register("damage_spells_work_blood", () -> (helper) -> WandSpellcastTests.damage_spells_deduct_mana_from_wand_and_award_expertise(helper, SpellPayloadsPM.BLOOD_DAMAGE.get()));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> DAMAGE_SPELLS_WORK_INFERNAL = Services.TEST_FUNCTIONS_REGISTRY.register("damage_spells_work_infernal", () -> (helper) -> WandSpellcastTests.damage_spells_deduct_mana_from_wand_and_award_expertise(helper, SpellPayloadsPM.FLAME_DAMAGE.get()));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> DAMAGE_SPELLS_WORK_VOID = Services.TEST_FUNCTIONS_REGISTRY.register("damage_spells_work_void", () -> (helper) -> WandSpellcastTests.damage_spells_deduct_mana_from_wand_and_award_expertise(helper, SpellPayloadsPM.VOID_DAMAGE.get()));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> DAMAGE_SPELLS_WORK_HALLOWED = Services.TEST_FUNCTIONS_REGISTRY.register("damage_spells_work_hallowed", () -> (helper) -> WandSpellcastTests.damage_spells_deduct_mana_from_wand_and_award_expertise(helper, SpellPayloadsPM.HOLY_DAMAGE.get()));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> SPELL_MANA_COST_ISOLATED_TO_PAYLOAD_SOURCE_EARTH_DAMAGE = Services.TEST_FUNCTIONS_REGISTRY.register("spell_mana_cost_isolated_to_payload_source_earth_damage", () -> (helper) -> SpellPackageTests.spell_mana_cost_isolated_to_payload_source(helper, SpellPayloadsPM.EARTH_DAMAGE.get(), Sources.EARTH));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> SPELL_MANA_COST_ISOLATED_TO_PAYLOAD_SOURCE_FROST_DAMAGE = Services.TEST_FUNCTIONS_REGISTRY.register("spell_mana_cost_isolated_to_payload_source_frost_damage", () -> (helper) -> SpellPackageTests.spell_mana_cost_isolated_to_payload_source(helper, SpellPayloadsPM.FROST_DAMAGE.get(), Sources.SEA));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> SPELL_MANA_COST_ISOLATED_TO_PAYLOAD_SOURCE_LIGHTNING_DAMAGE = Services.TEST_FUNCTIONS_REGISTRY.register("spell_mana_cost_isolated_to_payload_source_lightning_damage", () -> (helper) -> SpellPackageTests.spell_mana_cost_isolated_to_payload_source(helper, SpellPayloadsPM.LIGHTNING_DAMAGE.get(), Sources.SKY));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> SPELL_MANA_COST_ISOLATED_TO_PAYLOAD_SOURCE_SOLAR_DAMAGE = Services.TEST_FUNCTIONS_REGISTRY.register("spell_mana_cost_isolated_to_payload_source_solar_damage", () -> (helper) -> SpellPackageTests.spell_mana_cost_isolated_to_payload_source(helper, SpellPayloadsPM.SOLAR_DAMAGE.get(), Sources.SUN));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> SPELL_MANA_COST_ISOLATED_TO_PAYLOAD_SOURCE_LUNAR_DAMAGE = Services.TEST_FUNCTIONS_REGISTRY.register("spell_mana_cost_isolated_to_payload_source_lunar_damage", () -> (helper) -> SpellPackageTests.spell_mana_cost_isolated_to_payload_source(helper, SpellPayloadsPM.LUNAR_DAMAGE.get(), Sources.MOON));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> SPELL_MANA_COST_ISOLATED_TO_PAYLOAD_SOURCE_BLOOD_DAMAGE = Services.TEST_FUNCTIONS_REGISTRY.register("spell_mana_cost_isolated_to_payload_source_blood_damage", () -> (helper) -> SpellPackageTests.spell_mana_cost_isolated_to_payload_source(helper, SpellPayloadsPM.BLOOD_DAMAGE.get(), Sources.BLOOD));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> SPELL_MANA_COST_ISOLATED_TO_PAYLOAD_SOURCE_FLAME_DAMAGE = Services.TEST_FUNCTIONS_REGISTRY.register("spell_mana_cost_isolated_to_payload_source_flame_damage", () -> (helper) -> SpellPackageTests.spell_mana_cost_isolated_to_payload_source(helper, SpellPayloadsPM.FLAME_DAMAGE.get(), Sources.INFERNAL));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> SPELL_MANA_COST_ISOLATED_TO_PAYLOAD_SOURCE_VOID_DAMAGE = Services.TEST_FUNCTIONS_REGISTRY.register("spell_mana_cost_isolated_to_payload_source_void_damage", () -> (helper) -> SpellPackageTests.spell_mana_cost_isolated_to_payload_source(helper, SpellPayloadsPM.VOID_DAMAGE.get(), Sources.VOID));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> SPELL_MANA_COST_ISOLATED_TO_PAYLOAD_SOURCE_HOLY_DAMAGE = Services.TEST_FUNCTIONS_REGISTRY.register("spell_mana_cost_isolated_to_payload_source_holy_damage", () -> (helper) -> SpellPackageTests.spell_mana_cost_isolated_to_payload_source(helper, SpellPayloadsPM.HOLY_DAMAGE.get(), Sources.HALLOWED));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> SPELL_MANA_COST_ISOLATED_TO_PAYLOAD_SOURCE_BREAK = Services.TEST_FUNCTIONS_REGISTRY.register("spell_mana_cost_isolated_to_payload_source_break", () -> (helper) -> SpellPackageTests.spell_mana_cost_isolated_to_payload_source(helper, SpellPayloadsPM.BREAK.get(), Sources.EARTH));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> SPELL_MANA_COST_ISOLATED_TO_PAYLOAD_SOURCE_CONJURE_STONE = Services.TEST_FUNCTIONS_REGISTRY.register("spell_mana_cost_isolated_to_payload_source_conjure_stone", () -> (helper) -> SpellPackageTests.spell_mana_cost_isolated_to_payload_source(helper, SpellPayloadsPM.CONJURE_STONE.get(), Sources.EARTH));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> SPELL_MANA_COST_ISOLATED_TO_PAYLOAD_SOURCE_CONJURE_WATER = Services.TEST_FUNCTIONS_REGISTRY.register("spell_mana_cost_isolated_to_payload_source_conjure_water", () -> (helper) -> SpellPackageTests.spell_mana_cost_isolated_to_payload_source(helper, SpellPayloadsPM.CONJURE_WATER.get(), Sources.SEA));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> SPELL_MANA_COST_ISOLATED_TO_PAYLOAD_SOURCE_SHEAR = Services.TEST_FUNCTIONS_REGISTRY.register("spell_mana_cost_isolated_to_payload_source_shear", () -> (helper) -> SpellPackageTests.spell_mana_cost_isolated_to_payload_source(helper, SpellPayloadsPM.SHEAR.get(), Sources.SKY));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> SPELL_MANA_COST_ISOLATED_TO_PAYLOAD_SOURCE_FLIGHT = Services.TEST_FUNCTIONS_REGISTRY.register("spell_mana_cost_isolated_to_payload_source_flight", () -> (helper) -> SpellPackageTests.spell_mana_cost_isolated_to_payload_source(helper, SpellPayloadsPM.FLIGHT.get(), Sources.SKY));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> SPELL_MANA_COST_ISOLATED_TO_PAYLOAD_SOURCE_HEALING = Services.TEST_FUNCTIONS_REGISTRY.register("spell_mana_cost_isolated_to_payload_source_healing", () -> (helper) -> SpellPackageTests.spell_mana_cost_isolated_to_payload_source(helper, SpellPayloadsPM.HEALING.get(), Sources.SUN));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> SPELL_MANA_COST_ISOLATED_TO_PAYLOAD_SOURCE_CONJURE_LIGHT = Services.TEST_FUNCTIONS_REGISTRY.register("spell_mana_cost_isolated_to_payload_source_conjure_light", () -> (helper) -> SpellPackageTests.spell_mana_cost_isolated_to_payload_source(helper, SpellPayloadsPM.CONJURE_LIGHT.get(), Sources.SUN));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> SPELL_MANA_COST_ISOLATED_TO_PAYLOAD_SOURCE_POLYMORPH_WOLF = Services.TEST_FUNCTIONS_REGISTRY.register("spell_mana_cost_isolated_to_payload_source_polymorph_wolf", () -> (helper) -> SpellPackageTests.spell_mana_cost_isolated_to_payload_source(helper, SpellPayloadsPM.POLYMORPH_WOLF.get(), Sources.MOON));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> SPELL_MANA_COST_ISOLATED_TO_PAYLOAD_SOURCE_POLYMORPH_SHEEP = Services.TEST_FUNCTIONS_REGISTRY.register("spell_mana_cost_isolated_to_payload_source_polymorph_sheep", () -> (helper) -> SpellPackageTests.spell_mana_cost_isolated_to_payload_source(helper, SpellPayloadsPM.POLYMORPH_SHEEP.get(), Sources.MOON));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> SPELL_MANA_COST_ISOLATED_TO_PAYLOAD_SOURCE_CONJURE_ANIMAL = Services.TEST_FUNCTIONS_REGISTRY.register("spell_mana_cost_isolated_to_payload_source_conjure_animal", () -> (helper) -> SpellPackageTests.spell_mana_cost_isolated_to_payload_source(helper, SpellPayloadsPM.CONJURE_ANIMAL.get(), Sources.BLOOD));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> SPELL_MANA_COST_ISOLATED_TO_PAYLOAD_SOURCE_CONJURE_LAVA = Services.TEST_FUNCTIONS_REGISTRY.register("spell_mana_cost_isolated_to_payload_source_conjure_lava", () -> (helper) -> SpellPackageTests.spell_mana_cost_isolated_to_payload_source(helper, SpellPayloadsPM.CONJURE_LAVA.get(), Sources.INFERNAL));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> SPELL_MANA_COST_ISOLATED_TO_PAYLOAD_SOURCE_DRAIN_SOUL = Services.TEST_FUNCTIONS_REGISTRY.register("spell_mana_cost_isolated_to_payload_source_drain_soul", () -> (helper) -> SpellPackageTests.spell_mana_cost_isolated_to_payload_source(helper, SpellPayloadsPM.DRAIN_SOUL.get(), Sources.INFERNAL));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> SPELL_MANA_COST_ISOLATED_TO_PAYLOAD_SOURCE_TELEPORT = Services.TEST_FUNCTIONS_REGISTRY.register("spell_mana_cost_isolated_to_payload_source_teleport", () -> (helper) -> SpellPackageTests.spell_mana_cost_isolated_to_payload_source(helper, SpellPayloadsPM.TELEPORT.get(), Sources.VOID));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> SPELL_MANA_COST_ISOLATED_TO_PAYLOAD_SOURCE_CONSECRATE = Services.TEST_FUNCTIONS_REGISTRY.register("spell_mana_cost_isolated_to_payload_source_consecrate", () -> (helper) -> SpellPackageTests.spell_mana_cost_isolated_to_payload_source(helper, SpellPayloadsPM.CONSECRATE.get(), Sources.HALLOWED));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> SPELL_MANA_COST_EARTH_DAMAGE_POWER_1 = Services.TEST_FUNCTIONS_REGISTRY.register("spell_mana_cost_earth_damage_power_1", () -> SpellPackageTests::spell_mana_cost_earth_damage_power_1);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> SPELL_MANA_COST_EARTH_DAMAGE_POWER_5 = Services.TEST_FUNCTIONS_REGISTRY.register("spell_mana_cost_earth_damage_power_5", () -> SpellPackageTests::spell_mana_cost_earth_damage_power_5);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> SPELL_MANA_COST_FLAME_DAMAGE_POWER_3_DURATION_2 = Services.TEST_FUNCTIONS_REGISTRY.register("spell_mana_cost_flame_damage_power_3_duration_2", () -> SpellPackageTests::spell_mana_cost_flame_damage_power_3_duration_2);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> SPELL_MANA_COST_BREAK_POWER_2_SILK_TOUCH = Services.TEST_FUNCTIONS_REGISTRY.register("spell_mana_cost_break_power_2_silk_touch", () -> SpellPackageTests::spell_mana_cost_break_power_2_silk_touch);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> SPELL_MANA_COST_VEHICLE_SELF = Services.TEST_FUNCTIONS_REGISTRY.register("spell_mana_cost_vehicle_self", () -> SpellPackageTests::spell_mana_cost_vehicle_self);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> SPELL_MANA_COST_VEHICLE_BOLT = Services.TEST_FUNCTIONS_REGISTRY.register("spell_mana_cost_vehicle_bolt", () -> SpellPackageTests::spell_mana_cost_vehicle_bolt);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> SPELL_MANA_COST_VEHICLE_PROJECTILE = Services.TEST_FUNCTIONS_REGISTRY.register("spell_mana_cost_vehicle_projectile", () -> SpellPackageTests::spell_mana_cost_vehicle_projectile);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> SPELL_MANA_COST_MOD_AMPLIFY = Services.TEST_FUNCTIONS_REGISTRY.register("spell_mana_cost_mod_amplify", () -> SpellPackageTests::spell_mana_cost_mod_amplify);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> SPELL_MANA_COST_MOD_BURST = Services.TEST_FUNCTIONS_REGISTRY.register("spell_mana_cost_mod_burst", () -> SpellPackageTests::spell_mana_cost_mod_burst);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> SPELL_MANA_COST_MOD_FORK = Services.TEST_FUNCTIONS_REGISTRY.register("spell_mana_cost_mod_fork", () -> SpellPackageTests::spell_mana_cost_mod_fork);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> SPELL_MANA_COST_MOD_MINE = Services.TEST_FUNCTIONS_REGISTRY.register("spell_mana_cost_mod_mine", () -> SpellPackageTests::spell_mana_cost_mod_mine);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> SPELL_MANA_COST_MOD_QUICKEN = Services.TEST_FUNCTIONS_REGISTRY.register("spell_mana_cost_mod_quicken", () -> SpellPackageTests::spell_mana_cost_mod_quicken);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> SPELL_MANA_COST_MOD_ORDER_INDEPENDENT = Services.TEST_FUNCTIONS_REGISTRY.register("spell_mana_cost_mod_order_independent", () -> SpellPackageTests::spell_mana_cost_mod_order_independent);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> SPELL_COOLDOWN_BASE = Services.TEST_FUNCTIONS_REGISTRY.register("spell_cooldown_base", () -> SpellPackageTests::spell_cooldown_base);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> SPELL_COOLDOWN_QUICKEN_HASTE_1 = Services.TEST_FUNCTIONS_REGISTRY.register("spell_cooldown_quicken_haste_1", () -> (helper) -> SpellPackageTests.spell_cooldown_quicken(helper, 1, 25));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> SPELL_COOLDOWN_QUICKEN_HASTE_2 = Services.TEST_FUNCTIONS_REGISTRY.register("spell_cooldown_quicken_haste_2", () -> (helper) -> SpellPackageTests.spell_cooldown_quicken(helper, 2, 20));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> SPELL_COOLDOWN_QUICKEN_HASTE_3 = Services.TEST_FUNCTIONS_REGISTRY.register("spell_cooldown_quicken_haste_3", () -> (helper) -> SpellPackageTests.spell_cooldown_quicken(helper, 3, 15));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> SPELL_COOLDOWN_QUICKEN_HASTE_4 = Services.TEST_FUNCTIONS_REGISTRY.register("spell_cooldown_quicken_haste_4", () -> (helper) -> SpellPackageTests.spell_cooldown_quicken(helper, 4, 10));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> SPELL_COOLDOWN_QUICKEN_HASTE_5 = Services.TEST_FUNCTIONS_REGISTRY.register("spell_cooldown_quicken_haste_5", () -> (helper) -> SpellPackageTests.spell_cooldown_quicken(helper, 5, 5));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> SPELL_COOLDOWN_QUICKEN_HASTE_6 = Services.TEST_FUNCTIONS_REGISTRY.register("spell_cooldown_quicken_haste_6", () -> (helper) -> SpellPackageTests.spell_cooldown_quicken(helper, 6, 0));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> SPELL_COOLDOWN_QUICKEN_HASTE_7 = Services.TEST_FUNCTIONS_REGISTRY.register("spell_cooldown_quicken_haste_7", () -> (helper) -> SpellPackageTests.spell_cooldown_quicken(helper, 7, 0));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> SPELL_PACKAGE_NBT_ROUNDTRIP = Services.TEST_FUNCTIONS_REGISTRY.register("spell_package_nbt_roundtrip", () -> SpellPackageTests::spell_package_nbt_roundtrip);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> SPELL_ACTIVE_MOD_COUNT_0 = Services.TEST_FUNCTIONS_REGISTRY.register("spell_active_mod_count_0", () -> SpellPackageTests::spell_active_mod_count_0);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> SPELL_ACTIVE_MOD_COUNT_1 = Services.TEST_FUNCTIONS_REGISTRY.register("spell_active_mod_count_1", () -> SpellPackageTests::spell_active_mod_count_1);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> SPELL_ACTIVE_MOD_COUNT_2 = Services.TEST_FUNCTIONS_REGISTRY.register("spell_active_mod_count_2", () -> SpellPackageTests::spell_active_mod_count_2);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> SPELL_ACTIVE_MOD_COUNT_IGNORES_EMPTY_MOD = Services.TEST_FUNCTIONS_REGISTRY.register("spell_active_mod_count_ignores_empty_mod", () -> SpellPackageTests::spell_active_mod_count_ignores_empty_mod);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> SPELL_IS_VALID_COMPLETE = Services.TEST_FUNCTIONS_REGISTRY.register("spell_is_valid_complete", () -> SpellPackageTests::spell_is_valid_complete);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> SPELL_IS_INVALID_EMPTY_NAME = Services.TEST_FUNCTIONS_REGISTRY.register("spell_is_invalid_empty_name", () -> SpellPackageTests::spell_is_invalid_empty_name);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> SPELL_IS_INVALID_EMPTY_VEHICLE = Services.TEST_FUNCTIONS_REGISTRY.register("spell_is_invalid_empty_vehicle", () -> SpellPackageTests::spell_is_invalid_empty_vehicle);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> SPELL_IS_INVALID_EMPTY_PAYLOAD = Services.TEST_FUNCTIONS_REGISTRY.register("spell_is_invalid_empty_payload", () -> SpellPackageTests::spell_is_invalid_empty_payload);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> SPELL_IS_INVALID_NULL_NAME = Services.TEST_FUNCTIONS_REGISTRY.register("spell_is_invalid_null_name", () -> SpellPackageTests::spell_is_invalid_null_name);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> SPELL_IS_INVALID_NULL_VEHICLE = Services.TEST_FUNCTIONS_REGISTRY.register("spell_is_invalid_null_vehicle", () -> SpellPackageTests::spell_is_invalid_null_vehicle);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> SPELL_IS_INVALID_NULL_PAYLOAD = Services.TEST_FUNCTIONS_REGISTRY.register("spell_is_invalid_null_payload", () -> SpellPackageTests::spell_is_invalid_null_payload);

    // Auto charger tests
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> AUTO_CHARGER_OUTPUT_ALLOWS_CHARGEABLE_ITEMS = Services.TEST_FUNCTIONS_REGISTRY.register("auto_charger_output_allows_chargeable_items", () -> AutoChargerTests::auto_charger_output_allows_chargeable_items);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> AUTO_CHARGER_OUTPUT_DOES_NOT_ALLOW_UNCHARGEABLE_ITEMS = Services.TEST_FUNCTIONS_REGISTRY.register("auto_charger_output_does_not_allow_unchargeable_items", () -> AutoChargerTests::auto_charger_output_does_not_allow_unchargeable_items);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> AUTO_CHARGER_CAN_HAVE_CHARGEABLE_ITEMS_INSERTED = Services.TEST_FUNCTIONS_REGISTRY.register("auto_charger_can_have_chargeable_items_inserted", () -> AutoChargerTests::auto_charger_can_have_chargeable_items_inserted);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> AUTO_CHARGER_CANNOT_HAVE_UNCHARGEABLE_ITEMS_INSERTED = Services.TEST_FUNCTIONS_REGISTRY.register("auto_charger_cannot_have_unchargeable_items_inserted", () -> AutoChargerTests::auto_charger_cannot_have_unchargeable_items_inserted);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> AUTO_CHARGER_CAN_HAVE_CHARGEABLE_ITEMS_REMOVED = Services.TEST_FUNCTIONS_REGISTRY.register("auto_charger_can_have_chargeable_items_removed", () -> AutoChargerTests::auto_charger_can_have_chargeable_items_removed);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> AUTO_CHARGER_SIPHONS_INTO_CHARGEABLE_ITEMS = Services.TEST_FUNCTIONS_REGISTRY.register("auto_charger_siphons_into_chargeable_items", () -> AutoChargerTests::auto_charger_siphons_into_chargeable_items);

    // Mana battery tests
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> MANA_BATTERY_CAN_HAVE_ITS_MENU_OPENED = Services.TEST_FUNCTIONS_REGISTRY.register("mana_battery_can_have_its_menu_opened", () -> ManaBatteryTests::mana_battery_can_have_its_menu_opened);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> MANA_BATTERY_OUTPUT_ALLOWS_CHARGEABLE_ITEMS = Services.TEST_FUNCTIONS_REGISTRY.register("mana_battery_output_allows_chargeable_items", () -> ManaBatteryTests::mana_battery_output_allows_chargeable_items);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> MANA_BATTERY_OUTPUT_DOES_NOT_ALLOW_UNCHARGEABLE_ITEMS = Services.TEST_FUNCTIONS_REGISTRY.register("mana_battery_output_does_not_allow_unchargeable_items", () -> ManaBatteryTests::mana_battery_output_does_not_allow_unchargeable_items);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> MANA_BATTERY_INPUT_ALLOWS_ESSENCE = Services.TEST_FUNCTIONS_REGISTRY.register("mana_battery_input_allows_essence", () -> ManaBatteryTests::mana_battery_input_allows_essence);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> MANA_BATTERY_INPUT_ALLOWS_WANDS = Services.TEST_FUNCTIONS_REGISTRY.register("mana_battery_input_allows_wands", () -> ManaBatteryTests::mana_battery_input_allows_wands);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> MANA_BATTERY_SIPHONS_FROM_NEARBY_FONTS = Services.TEST_FUNCTIONS_REGISTRY.register("mana_battery_siphons_from_nearby_fonts", () -> ManaBatteryTests::mana_battery_siphons_from_nearby_fonts);

    // Mana font tests
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> MANA_FONT_SIPHONED_BY_WAND = Services.TEST_FUNCTIONS_REGISTRY.register("mana_font_siphoned_by_wand", () -> ManaFontTests::mana_font_siphoned_by_wand);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> MANA_FONT_RECHARGES = Services.TEST_FUNCTIONS_REGISTRY.register("mana_font_recharges", () -> ManaFontTests::mana_font_recharges);

    // Wand charger tests
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CHARGER_CAN_HAVE_ITS_MENU_OPENED = Services.TEST_FUNCTIONS_REGISTRY.register("wand_charger_can_have_its_menu_opened", () -> WandChargerTests::wand_charger_can_have_its_menu_opened);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CHARGER_OUTPUT_ALLOWS_CHARGEABLE_ITEMS = Services.TEST_FUNCTIONS_REGISTRY.register("wand_charger_output_allows_chargeable_items", () -> WandChargerTests::wand_charger_output_allows_chargeable_items);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CHARGER_OUTPUT_DOES_NOT_ALLOW_UNCHARGEABLE_ITEMS = Services.TEST_FUNCTIONS_REGISTRY.register("wand_charger_output_does_not_allow_unchargeable_items", () -> WandChargerTests::wand_charger_output_does_not_allow_unchargeable_items);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CHARGER_INPUT_ALLOWS_ESSENCE = Services.TEST_FUNCTIONS_REGISTRY.register("wand_charger_input_allows_essence", () -> WandChargerTests::wand_charger_input_allows_essence);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CHARGER_INPUT_DOES_NOT_ALLOW_NON_ESSENCE = Services.TEST_FUNCTIONS_REGISTRY.register("wand_charger_input_does_not_allow_non_essence", () -> WandChargerTests::wand_charger_input_does_not_allow_non_essence);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CHARGER_CAN_CHARGE_WITH_RIGHT_ITEMS = Services.TEST_FUNCTIONS_REGISTRY.register("wand_charger_can_charge_with_right_items", () -> WandChargerTests::wand_charger_can_charge_with_right_items);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> WAND_CHARGER_DO_CHARGE_WITH_RIGHT_ITEMS = Services.TEST_FUNCTIONS_REGISTRY.register("wand_charger_do_charge_with_right_items", () -> WandChargerTests::wand_charger_do_charge_with_right_items);
}
